//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elasund {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Elasund : global::System.Configuration.ApplicationSettingsBase {
        
        private static Elasund defaultInstance = ((Elasund)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Elasund())));
        
        public static Elasund Default {
            get {
                return defaultInstance;
            }
        }
    }
}
